"""Add created_at to PhishingURL

Revision ID: 1e674edf592d
Revises: d14b19dcb9ba
Create Date: 2025-01-12 00:03:33.111229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e674edf592d'
down_revision = 'd14b19dcb9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_url', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
