"""Add created_at to PhishingURL

Revision ID: d14b19dcb9ba
Revises: 543ac4f63deb
Create Date: 2025-01-11 23:56:14.244339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14b19dcb9ba'
down_revision = '543ac4f63deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_url', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
